# Generated by Django 5.0.14 on 2025-10-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('PATIENT', 'Patient'), ('RECEPTIONIST', 'Receptionist'), ('PHARMACIST', 'Pharmacist'), ('LAB_TECH', 'Lab Technician'), ('CHO', 'Community Health Officer (CHO)'), ('CHEW', 'Community Health Extension Worker (CHEW)'), ('LAB_ATTENDANT', 'Lab Attendant'), ('PHARMACY_TECHNICIAN', 'Pharmacy Technician'), ('HEALTH_RECORD_TECHNICIAN', 'Health Record Technician')], default='PATIENT', max_length=30),
        ),
    ]
