# Generated by Django 5.0.14 on 2025-10-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_facilityexcelupload_user_hospital_clinic_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facility_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
