# Generated by Django 5.0.14 on 2025-10-27 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('complete', 'Complete')], max_length=16)),
                ('module', models.CharField(help_text='App label where the action occurred', max_length=64)),
                ('model', models.CharField(help_text='Model name affected', max_length=64)),
                ('action_description', models.TextField(blank=True, null=True)),
                ('object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('staff_name', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_id', models.CharField(blank=True, max_length=255, null=True)),
                ('hospital_clinic_id', models.CharField(blank=True, max_length=255, null=True)),
                ('action_datetime', models.DateTimeField()),
                ('action_date', models.DateField()),
                ('action_time', models.TimeField()),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-action_datetime',),
                'indexes': [models.Index(fields=['module', 'model', 'action_type', 'action_date'], name='audit_activ_module_43435c_idx'), models.Index(fields=['staff_id', 'hospital_clinic_id', 'action_date'], name='audit_activ_staff_i_f57815_idx')],
            },
        ),
    ]
