# Generated by Django 5.0.14 on 2025-10-27 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='baby_hospital_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='baby_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='mother_member_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='vaccine_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['mother_member_id', 'baby_hospital_id', 'scheduled_date'], name='audit_activ_mother__0e097e_idx'),
        ),
    ]
