# Generated by Django 5.2.7 on 2025-10-16 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmunizationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('DUE', 'Due'), ('DONE', 'Done'), ('MISSED', 'Missed')], default='DUE', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immunizations', to='patients.babyprofile')),
            ],
        ),
    ]
