# Generated by Django 5.0.14 on 2025-10-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immunization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmunizationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('interval_value', models.PositiveIntegerField(help_text='Number of days/weeks/months after birth')),
                ('interval_unit', models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='immunizationschedule',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
