# Generated by Django 5.0.14 on 2025-10-22 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immunization', '0002_immunizationmaster_and_more'),
        ('patients', '0005_medicalrecordattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmunizationRuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reschedule_window_days', models.IntegerField(default=30)),
                ('pre_due_reminder_days', models.IntegerField(default=3)),
                ('observation_reminder_hours', models.IntegerField(default=24)),
                ('missed_after_days', models.IntegerField(default=2)),
                ('hospital_name', models.CharField(default='Medical Care Hospital', max_length=200)),
                ('certificate_footer_note', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='immunizationschedule',
            name='administered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='immunizationschedule',
            name='administered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_immunizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='immunizationschedule',
            name='administration_site',
            field=models.CharField(blank=True, help_text='e.g., Left Arm, Right Thigh', max_length=64),
        ),
        migrations.AddField(
            model_name='immunizationschedule',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='immunizationschedule',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_immunizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='immunizationschedule',
            name='batch_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='immunizationschedule',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='immunizationschedule',
            name='post_observation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='immunizationschedule',
            name='reschedule_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='immunizationschedule',
            name='rescheduled_for',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='immunizationschedule',
            name='visible_to_mother',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='immunizationschedule',
            name='status',
            field=models.CharField(choices=[('DUE', 'Pending'), ('DONE', 'Done'), ('MISSED', 'Missed')], default='DUE', max_length=10),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=64)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='WEB', max_length=20)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImmunizationApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='immunization_approvals', to=settings.AUTH_USER_MODEL)),
                ('baby', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='immunization_approval', to='patients.babyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ImmunizationCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, upload_to='certificates/')),
                ('data_snapshot', models.JSONField(blank=True, default=dict)),
                ('baby', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='immunization_certificate', to='patients.babyprofile')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ADMINISTERED', 'Administered'), ('OBSERVATION_ADDED', 'Observation Added'), ('RESCHEDULED', 'Rescheduled'), ('STATUS_CHANGED', 'Status Changed'), ('APPROVED', 'Approved'), ('CERTIFICATE_GENERATED', 'Certificate Generated')], max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_events', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='immunization.immunizationschedule')),
            ],
        ),
    ]
