# Generated by Django 5.0.14 on 2025-10-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immunization', '0003_immunizationruleconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='immunizationschedule',
            name='administered_hospital_clinic_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='immunizationschedule',
            name='administered_staff_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='immunizationschedule',
            name='administered_staff_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
