# Generated by Django 5.0.14 on 2025-10-19 07:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('antenatal', 'Antenatal Care'), ('postnatal', 'Postnatal Care'), ('immunization', 'Newborn Immunization')], unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body', ckeditor.fields.RichTextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='care_pages/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Care Page',
                'verbose_name_plural': 'Care Pages',
                'ordering': ['slug'],
            },
        ),
    ]
