# Generated by Django 5.2.7 on 2025-10-16 20:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_motherprofile_profile_picture'),
    ]

    def populate_member_ids(apps, schema_editor):
        MotherProfile = apps.get_model('patients', 'MotherProfile')
        # Collect existing ids to avoid any accidental duplicates
        existing = set(
            MotherProfile.objects.exclude(member_id__isnull=True).values_list('member_id', flat=True)
        )
        for profile in MotherProfile.objects.all():
            if not profile.member_id:
                mid = f"MED-{uuid.uuid4().hex[:8].upper()}"
                while mid in existing:
                    mid = f"MED-{uuid.uuid4().hex[:8].upper()}"
                profile.member_id = mid
                profile.save(update_fields=['member_id'])
                existing.add(mid)

    operations = [
        migrations.AddField(
            model_name='motherprofile',
            name='member_id',
            field=models.CharField(blank=True, null=True, max_length=20),
        ),
        migrations.RunPython(populate_member_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='motherprofile',
            name='member_id',
            field=models.CharField(blank=True, null=True, max_length=20, unique=True),
        ),
    ]
