# Generated by Django 5.0.14 on 2025-10-19 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_babyprofile_registered_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecordAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='medical_records/')),
                ('type', models.CharField(choices=[('SCAN', 'Scan/Imaging'), ('TEST', 'Lab Test'), ('PRESCRIPTION', 'Prescription'), ('NOTE', 'Clinical Note')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='patients.medicalrecord')),
            ],
        ),
    ]
