# Generated by Django 5.0.14 on 2025-10-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_medicalrecordattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyprofile',
            name='hospital_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
