# Generated by Django 5.0.14 on 2025-10-22 11:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('casefiles', '0001_initial'),
        ('patients', '0006_babyprofile_hospital_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyCaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baby', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baby_case_file', to='patients.babyprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_baby_case_files', to=settings.AUTH_USER_MODEL)),
                ('primary_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_doctor_baby_case_files', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_baby_case_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BabyCaseBillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lab_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medication_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('PARTIAL', 'Partially Paid')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baby_case_billing_records', to='billing.invoice')),
                ('case_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='casefiles.babycasefile')),
            ],
        ),
        migrations.CreateModel(
            name='BabyCaseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='casefiles/babies/attachments/')),
                ('attachment_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baby_casefile_attachments', to=settings.AUTH_USER_MODEL)),
                ('case_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='casefiles.babycasefile')),
            ],
        ),
        migrations.CreateModel(
            name='BabyCaseActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='casefiles.babycasefile')),
            ],
        ),
        migrations.CreateModel(
            name='BabyLabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=255)),
                ('date_performed', models.DateField(default=django.utils.timezone.now)),
                ('result_text', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='casefiles/babies/lab_results/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REVIEWED', 'Reviewed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='casefiles.babycasefile')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_baby_lab_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BabyPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('route', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ISSUED', 'Issued'), ('DISPENSED', 'Dispensed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='casefiles.babycasefile')),
                ('prescribing_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baby_prescribed_medications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BabyVisitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_visit', models.DateTimeField(default=django.utils.timezone.now)),
                ('complaints', models.TextField()),
                ('examination_findings', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('recommended_tests', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='casefiles.babycasefile')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baby_visit_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
