# Generated by Django 5.2.7 on 2025-10-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='banner_image_url',
        ),
        migrations.RemoveField(
            model_name='center',
            name='hero_image_url',
        ),
        migrations.AddField(
            model_name='center',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='centers/'),
        ),
        migrations.AddField(
            model_name='center',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='centers/'),
        ),
    ]
