# Generated by Django 5.2.7 on 2025-10-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_remove_center_banner_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='centers/'),
        ),
    ]
